### ISSUE TITLE
error while cross-compiling v0.10.34 on MIPS architecture (openwrt 14.07)

### ISSUE THREAD

**Issue by artynet** [joyent/node#8901]
Hi folks,

I get this error when building the latest release on node on my openwrt embedded system. I always perform a shared build with the **v8 3.14.5 for MIPS (UTF8_REPLACE_INVALID patched)** and it usually all runs smoothly until the end. 

However, this time I get this error while compiling : 

```
../src/node.cc: In function 'v8::Handle<v8::Value> node::Umask(const v8::Arguments&)':
../src/node.cc:1430:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for (int i = 0; i < str.length(); i++) {
                                      ^
../src/node.cc: In function 'char** node::Init(int, char**)':
../src/node.cc:2982:17: error: 'class v8::Isolate' has no member named 'SetAbortOnUncaughtException'
   node_isolate->SetAbortOnUncaughtException(ShouldAbortOnUncaughtException);
                 ^
make[4]: *** [/home/arturo/temp/openwrt-stable-14.07/build_dir/target-mips_34kc_uClibc-0.9.33.2/node-v0.10.34/out/Release/obj.target/node/src/node.o] Error 1
make[4]: Leaving directory `/home/arturo/temp/openwrt-stable-14.07/build_dir/target-mips_34kc_uClibc-0.9.33.2/node-v0.10.34/out'
make[3]: *** [node] Error 2
make[3]: Leaving directory `/home/arturo/temp/openwrt-stable-14.07/build_dir/target-mips_34kc_uClibc-0.9.33.2/node-v0.10.34'
make[2]: *** [/home/arturo/temp/openwrt-stable-14.07/build_dir/target-mips_34kc_uClibc-0.9.33.2/node-v0.10.34/.built] Error 2
make[2]: Leaving directory `/home/arturo/temp/openwrt-stable-14.07/package/linino/node'
make[1]: *** [package//node/compile] Error 2
make[1]: Leaving directory `/home/arturo/temp/openwrt-stable-14.07'
make: *** [package/node/compile] Error 2
```
any hints on this ? Thanks in advance, Arturo.

**Comment by Suxsem** [comment]
I'm getting the same error and I didn't understood misterdjules suggestion...
For now i'm stick with 0.10.33 but please fix :)

**Comment by Suxsem** [comment]
Oh wait...i get this error on 0.10.33 as well! What can i do to fix it?

**Comment by misterdjules** [comment]
@artynet I think that you have [another build problem with v0.12 that is tracked in another issue](https://github.com/joyent/node/issues/9167). Since this issue is about v0.10 though, can we close it?

Thanks!

**Comment by artynet** [comment]
Yes Jules, thank you very much. With your patch I am able to build node version 0.10.34 and on. Regards, Arturo

**Comment by misterdjules** [comment]
@artynet Excellent! Does v0.10 run correctly? That is, do you get the same floating point exception as in https://github.com/joyent/node/issues/9167#issuecomment-73732730?

Anyway, closing this issue, but I hope we can find a solution for https://github.com/joyent/node/issues/9167 soon :)

**Comment by artynet** [comment]
the v0.10x series have always been running smoothly on my plathorm, and this kind of issue was never reported. I'd like to solve the v0.12 issue to leverage the full benefis of the v8 platform for MIPS since they have full support from branch 3.2x.

I have just built the new source but I can't test them unitl tomorrow morning.

   Regards, again

**Comment by misterdjules** [comment]
@artynet Great, thanks for the additional info.
